name: Simulated testing using verilator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  simulate:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -GNinja

    - name: Build simulation
      run: ninja -C ${{github.workspace}}/build build

    - name: Simulate
      # Enable -k option to simulate every module even if one fails
      run: ninja -C ${{github.workspace}}/build -k 0 tests &&
        # Checks if there is any testdata
        ls -A1q ${{github.workspace}}/build/tests/testdata/ | grep -q . && 
        # Check if there is any fail in that testdata
        grep -qe "[^;]*;0;" ${{github.workspace}}/build/tests/testdata/*

    - name: Generate reports
      run: ninja -C ${{github.workspace}}/build md_report

    - name: Write summary
      run: cat ${{github.workspace}}/build/test-report.md >> $GITHUB_STEP_SUMMARY
