name: Simulated testing using verilator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  simulate:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build simulation
      run: make -C ${{github.workspace}}/build build

    - name: Simulate
      run: make -C ${{github.workspace}}/build -k tests

    - name: Generate reports
      if: (steps.simulate.outcome == 'failure') || (steps.simulate.output == 'success')
      run: make -C ${{github.workspace}}/build md_report

    - name: Write summary
      run: cat ${{github.workspace}}/build/test-report.md >> $GITHUB_STEP_SUMMARY
