name: Simulated testing using verilator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  simulate:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Simulate
      run: make -C ${{github.workspace}}/build tests

    - name: Generate reports
      run: make -C ${{github.workspace}}/build reports

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: ${{github.workspace}}/build/test-report.html

    - name: Write summary
      run: cat ${{github.workspace}}/build/test-report.md >> $GITHUB_STEP_SUMMARY
