name: Simulated testing using verilator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  simulate:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -GNinja

    - name: Build simulation
      run: ninja -C ${{github.workspace}}/build build

    - name: Simulate
      run: ninja -C ${{github.workspace}}/build -k tests
      continue-on-error: true

    - name: Generate reports
      run: ninja -C ${{github.workspace}}/build md_report

    - name: Write summary
      run: cat ${{github.workspace}}/build/test-report.md >> $GITHUB_STEP_SUMMARY
