name: Simulated testing using verilator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: make -C ${{github.workspace}}/build

    - name: Simulate
      run: make -C ${{github.workspace}}/build tests
